model_name: mobilenetv3_large_100.ra4_e3600_r224_in1k
save_name: mobilenetv3
num_classes: 10
epochs: 30
lr: 0.0005
optimizer: AdamW
weight_decay: 0.0001
batch_size: 16
image_size: 224
num_workers: 4
num_folds: 5
fold: null
random_seed: 42
early_stopping_patience: 5
mixed_precision: true
scheduler: CosineAnnealingLR
scheduler_params:
  T_max: 30
  eta_min: 0.000001
dataset_path: datasets
